### ISSUE TITLE
Tim treba da ima tri člana

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RS17/RS08-regex-machine#1]
Ne možete da radite projekat samostalno, osim ako radite na nekom postojećem projektu slobodnog softvera.

**Comment by Ulq1** [comment]
Пројекат је пријављен са колегом Дејан Бокић (индекс: 64/14, github username: MrDejan995), а он није додат у репозиторијум.

**Comment by ivan-cukic-matf** [comment]
Po prijavi projekta koju imam na serveru, kolega nije bio naveden, ali nije problem. Dodao sam ga u repozitorijum.
